yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  styled-components@*:
    dependencies:
      babel-plugin-macros: "*"
      babel-plugin-styled-components: "*"
      react-is: "*"

  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
